const icons = [
	'Baguette.svg',
	'Banana Split.svg',
	'Banana.svg',
	'BBQ.svg',
	'Beer.svg',
	'Boba.svg',
	'Bread.svg',
	'Breakfast.svg',
	'Burger.svg',
	'Burrito.svg',
	'Cheese cake.svg',
	'Chocolate.svg',
	'Chopsticks.svg',
	'Cocktail.svg',
	'Coffee.svg',
	'Cola Can.svg',
	'Cookies.svg',
	'Croissant.svg',
	'Cutlery.svg',
	'Dimsum.svg',
	'Donut.svg',
	'Fries.svg',
	'Hotdog.svg',
	'Ice block.svg',
	'Ice Cream.svg',
	'Juice.svg',
	'Kimbab.svg',
	'Lollipop.svg',
	'Milk.svg',
	'Mineral Water.svg',
	'Muffin.svg',
	'Onigiri.svg',
	'Pancake.svg',
	'Pie.svg',
	'Pizza.svg',
	'Ramen.svg',
	'Salad.svg',
	'Salmon Steak.svg',
	'Salt Pepper.svg',
	'Sandwich.svg',
	'Sauce.svg',
	'Sausage.svg',
	'Softdrink.svg',
	'Spaghetti.svg',
	'Steak.svg',
	'Sushi.svg',
	'Tart.svg',
	'Tea.svg',
	'Wine.svg',
];

export default icons;
